#!/usr/bin/env bash
#A bash script that performs a dns query.
dns_query ()
{
	sub_domains=("www" "lb-01" "web-01" "web-02")
	if [ "$#" -eq 2 ]
	then
		dig "$2.$1" +noall +answer | awk -v arg="$2" '{sub(/\.$/, "", $1); print "The subdomain " arg " is a " $4 " record and points to " $5}'
	elif [ "$#" -eq 1 ]
	then
		size="${#sub_domains[@]}"
		for ((i=0; i<"${size}"; i++))
		do
			dm="${sub_domains[i]}.$1"
			dig "${dm}" +noall +answer | awk -v arg="${sub_domains[i]}" '{sub(/\.$/, "", $1); print "The subdomain " arg " is a " $4 " record and points to " $5}'
		done
	fi
}
dns_query "${@}"
