#!/usr/bin/env bash
#A bash script that performs a dns query.
dns_query ()
{
    line=dig "$1" | tr ' ' '\n' | tail -2 | tr '\n' ' '
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
if [ "$#" -eq 2 ]
then
    dns_query "$1" "$2"
elif [ "$#" -eq 1 ]
then
    dns_query "$1" "www"
    dns_query "$1" "lb-01"
    dns_query "$1" "web-01"
    dns_query "$1" "web-02"
fi
