#!/usr/bin/env bash
#Install nginx web server
#Requirements:
#    Install nginx on your web-01
#    server
#    Nginx should be listening on port 80
#    When querying Nginx at its root / with a GET request
#    (requesting a page) using curl, it must return a page
#    that contains the string Hello World!
#    A Bash script that configures a new Ubuntu machine to respect
#    above requirements (this script will be run on the server itself)
#    Not allowed to use systemctl for restarting nginx

apt-get update && apt-get -y install nginx
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "server {
        listen  80;
        listen  [::]:80 default_server;
        root    /var/www/html;
        index   index.html index.htm;
}" > /etc/nginx/sites-available/default

service nginx restart
