#!/usr/bin/env bash
#Configures an Nginx server so that /redirect_me is redirecting
#to another page.
#Requirements:
#
#    The redirection must be a “301 Moved Permanently”

apt update -y
apt install nginx -y
tag=".htm;\n\n\tlocation \/redirect_me {\n\treturn 301 http:\/\/www.google.com;\n\t}"
sed -i "s/.htm;/$tag/" /etc/nginx/sites-available/default
service nginx restart
