#!/usr/bin/env bash
#Configures an Nginx server so that /redirect_me is redirecting
#to another page.
#Requirements:
#
#    The redirection must be a “301 Moved Permanently”

apt update -y
apt install nginx -y
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

echo "server {
        listen  80;
        listen  [::]:80 default_server;
        root    /etc/nginx/html;
        index   index.html index.htm;
}" > /etc/nginx/sites-available/default

tag="\\\n\tlocation \/redirect_me {\n\t\treturn 301 http:\/\/www.google.com;\n\t}"
sed -i "6i $tag" /etc/nginx/sites-available/default
service nginx restart
