#!/usr/bin/env bash
#Configures an Nginx server so that /redirect_me is redirecting
#to another page.
#Requirements:
#
#    The redirection must be a “301 Moved Permanently”

apt update -y
apt install nginx -y
var="\\\n\tlocation / redirect_me {\n\t\treturn 301 www.google.com;\n\t}"
sed -i "6i $var" /etc/nginx/sites-available/default
service nginx restart
