#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains
#the string Ceci n'est pas une page
#Requirements follows other previous tasks
#
#Requirements:
#
#    The redirection must be a “301 Moved Permanently”

apt update -y
apt install nginx -y
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

echo "server {
        listen  80;
        listen  [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        root    /etc/nginx/html;
        index   index.html index.htm;
}" > /etc/nginx/sites-available/default

tag="\\\n\tlocation \/redirect_me {\n\t\treturn 301 http:\/\/www.google.com;\n\t}"
sed -i "7i $tag" /etc/nginx/sites-available/default
touch /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
var="\\\n\terror_page 404 /404.html;\n\tlocation /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sed -i "11i $var" /etc/nginx/sites-available/default

service nginx restart
