#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page
#that contains the string Ceci n'est pas une page.
#Requirements:
#
#    The page must return an HTTP 404 error code
#    The page must contain the string Ceci n'est pas une page

apt update -y
apt install nginx -y
tag=".htm;\n\n\tlocation \/redirect_me {\n\treturn 301 http:\/\/www.google.com;\n\t}"
touch /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i "s/.htm;/$tag/" /etc/nginx/sites-available/default
sed -i "s/#error_page 404/error_page 404/" /etc/nginx/sites-available/default
service nginx restart
