#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains
#the string Ceci n'est pas une page
#Requirements follows other previous tasks
#
#Requirements:
#

apt-get update && apt-get -y install nginx;
mkdir -p /var/www/html;
echo "Hello World!" > /var/www/html/index.html;
echo "server {
        listen  80;
        listen  [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        root    /var/www/html;
        index   index.html index.htm;
}" > /etc/nginx/sites-available/default;

tag="\\\n\tlocation \/redirect_me {\n\t\treturn 301 http:\/\/www.google.com;\n\t}"
sed -i "7i $tag" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
var="\\\n\terror_page 404 /404.html;\n\tlocation /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sed -i "11i $var" /etc/nginx/sites-available/default

service nginx restart
