#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
#Ubuntu Focal(20.04LTS)
#version: 2.0 stable LTS
#
#Requirements:
#
#    Configure HAproxy so that it send traffic to web-01 and web-02
#    Distribute requests using a roundrobin algorithm
#    Make sure that HAproxy can be managed via an init script
#    Make sure that your servers are configured with the right
#    hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02

apt-get update && apt-get -y install haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/original_haproxy.cfg

printf "\n
frontend web-frontend
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 208571-web-01 34.229.68.65:80 check
        server 208571-web-02 34.203.29.98:80 check
" >> /etc/haproxy/haproxy.cfg

#Enables HAproxy to be managed via an init script
echo "ENABLED=1" >> /etc/default/haproxy

service haproxy restart
