#!/usr/bin/env bash
#A script that installs Apache webserver and
#returns the text "Hello Holberton" when queried
#at the root

apt-get update && apt-get -y install apache2
mkdir -p /var/www/html
echo "Hello Holberton" > /var/www/html/index.html

#ufw allow Apache
service apache2 restart
