#!/usr/bin/env bash
#A bash that fixes a container so that Nginx
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled
pkill apache2
sudo -u nginx service nginx start

