#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server
# Requirements:
#    Only use ssh single-character flags
#    You cannot use -l
#    You do not need to handle the case of a private key protected by a passphrase

ssh -i ~/.ssh/school ubuntu@34.229.68.65
